# Title of your homepage
title: ChangeLog of Brandname #(required)

# Website Description for search engines (optional)
description: "Keep yourself up to date with our new product features"

# replace this word in navigation bar. Ex: Productnews, ChangeLog, Updates
heading: Updates # (optional)

# absolute or relative path of logo
logo: /assets/images/logo.png #(required)

# Your Product's Website
website: https://changelog.site # (required)

# the base hostname & protocol for your site, 
# e.g. https://updates.changelog.site
# Note Don't put trailing slash https://updates.changelog.site/
url: "https://updates.changelog.site"  # (required)

baseurl: '' # optional


# Github username/repo where your code is hosted.
github: changelogsite/changelog # (required)

# remove this line if don't want to show Github Star Badge
star-badge: true  #(optional)

# remove this line if don't want to show Github Watch Badge
watch-badge: true #(optional)

# Show rss feed icon in menubar. To disable this comment below line by adding # as first character.
rss-feed-icon: true #(optional)

# Global site tag (gtag.js) - Google Analytics e.g. UA-MYANALYTICS
analytics:  #(recommended)

# https://changelog-site.disqus.com
# disqus-identifier: changelog-site  # (optional)

# Allow users to comment via facebook
fb-comment: true

# Allow search engines to index your changelog website
allow-searchengine: true #optional


# Do not change anything below this if you don't know Jekyll

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets"
    values:
      sitemap: false 
  -
    scope:
      path: "admin"
    values:
      sitemap: false 

permalink: /:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir:         _sass
  style:            compressed


plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap

pagination:
  enabled: true
  per_page: 5
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true